events {}

http {
    upstream backend_servers {
        server ontology-backend.railway.internal:4000;
    }

    upstream kafka_servers {
        server cs-554-ontology-bae7.railway.internal:3001;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend_servers/;
        }

        location /kafka/ {
            proxy_pass http://kafka_servers/;
        }

    }
}